name: new_ways_app
description: A new Flutter project.

publish_to: "none"

version: 0.0.3+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  fluttertoast: ^8.0.8
  intl: ^0.17.0
  uuid: ^3.0.4
  google_maps_flutter: ^2.0.10
  location: ^4.2.0
  cached_network_image: ^3.1.0
  contacts_service: ^0.6.3
  permission_handler: ^8.1.6
  get: ^4.3.8
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  dio: ^4.0.0
  date_time_picker: ^2.1.0
  flutter_form_builder: ^6.1.0+1
  flutter_chips_input: ^1.10.0
  form_builder_image_picker: ^1.0.0-nullsafety.0
  # web_socket_channel: ^2.1.0
  # flutter_inappwebview: ^5.3.2
  loading_overlay: ^0.3.0
  loading_animations: ^2.2.0
  platform_device_id: ^1.0.1
  flutter_neat_and_clean_calendar: ^0.2.3+11
  auto_animated: ^3.0.1
  mat_month_picker_dialog: ^1.0.1
  flutter_qr_reader: ^1.0.5
  awesome_notifications: ^0.0.6+12
  package_info_plus: ^1.3.0
  url_launcher: ^6.0.12
  bottom_navy_bar: ^6.0.0
  lottie: ^1.2.1
  carousel_slider: ^4.0.0
  intro_slider: ^3.0.2
  delayed_display: ^2.0.0
  geolocator: ^7.7.1
  # network_image_to_byte: ^0.0.1
  http: ^0.13.4
  image: ^3.0.8
  network_to_file_image: ^3.0.3
  path_provider: ^2.0.6
  flutter_app_badger: ^1.3.0
  workmanager: ^0.4.1
  flutter_background: ^1.0.2+2
  html_editor_enhanced: ^2.4.0+1
  flutter_html: ^2.1.5
  # flutter_cache_manager: ^3.1.3

dev_dependencies:
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.3.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/splash_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/others/
    - assets/

flutter_native_splash:
  color: "#000000"
  image: assets/images/splash.png
  fullscreen: true
